FROM ubuntu:18.04

ENV ACCEPT_EULA=Y
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y locales
RUN locale-gen en_US.UTF-8
ENV LANG=en_US.UTF-8

RUN apt-get install -y software-properties-common
RUN add-apt-repository -y -u ppa:ondrej/php 
RUN apt-get update

RUN apt-get install -y \
    apt-transport-https \
    cron \
    curl \
    git \
    gnupg2 \
    libpq-dev \
    unzip \
    vim \
    apache2

RUN apt-get update && apt-get install -y \
    php7.4 \
    php7.4-dev \
    php7.4-cli \
    php7.4-mbstring \
    php7.4-intl \
    php7.4-ldap \
    php7.4-pgsql \
    php7.4-soap \
    php7.4-xml \
    php7.4-sqlite \
    php-curl \
    php-pear \
    libapache2-mod-php7.4

RUN a2ensite default-ssl
RUN sed -i '/<Directory \/var\/www\/>/,/<\/Directory>/ s/AllowOverride None/AllowOverride All/' /etc/apache2/apache2.conf
RUN a2enmod rewrite 
RUN a2enmod ssl

RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list > /etc/apt/sources.list.d/mssql-release.list

RUN apt-get update && apt-get install -y msodbcsql17 mssql-tools unixodbc-dev

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && ln -s $(composer config --global home) /root/composer
ENV PATH=$PATH:/root/composer/vendor/bin COMPOSER_ALLOW_SUPERUSER=1

# install necessary locales
RUN echo "America/Recife" > /etc/timezone
RUN cp -p /usr/share/zoneinfo/America/Recife /etc/localtime
RUN dpkg-reconfigure -f noninteractive tzdata
RUN echo "pt_BR.UTF-8 UTF-8" > /etc/locale.gen
RUN locale-gen pt_BR.UTF-8
RUN dpkg-reconfigure --frontend=noninteractive locales
RUN update-locale LANG=pt_BR.UTF-8
ENV LC_ALL=pt_BR.UTF-8
ENV LANG=pt_BR.UTF-8
ENV LANGUAGE=pt_BR.UTF-8

COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh
EXPOSE 22 80
CMD ["/entrypoint.sh"]

